#!/bin/bash
ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

brew update
brew install wget vim nvm go cmake ctags bash-completion
brew install boost
brew install boost-python --with-python3
brew install tmux reattach-to-user-namespace

export GOROOT=/usr/local/opt/go/libexec
export PATH=$PATH:$GOROOT/bin

go get -u golang.org/x/tools/cmd/goimports
go get -u github.com/nsf/gocode
go get -u github.com/rogpeppe/godef
go get -u github.com/jstemmer/gotags
go get -u github.com/tools/godep

source $HOME/.nvm/nvm.sh
nvm install 6.10

wget https://raw.githubusercontent.com/git/git/master/contrib/completion/git-prompt.sh -O $HOME/.git-prompt.sh
wget https://raw.githubusercontent.com/git/git/master/contrib/completion/git-completion.bash -O $HOME/.git-completion.sh

cat ./aliases >> $HOME/.aliases
cat ./bashrc > $HOME/.bashrc
cat ./functions >>  $HOME/.functions
cat ./gitconfig > $HOME/.gitconfig
cat ./profile > $HOME/.profile
cat ./tmux.conf > $HOME/.tmux.conf
cat ./vimrc > $HOME/.vimrc

git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm

mkdir -p $HOME/.vim

source $HOME/.profile

vim +PluginInstall +qall
vim +GoInstallBinaries +qall
(
  cd $HOME/.vim/bundle/YouCompleteMe
  ./install.py --clang-completer --gocode-completer --tern-completer
)