# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH="/Users/jokyn/.oh-my-zsh"

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time oh-my-zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
ZSH_THEME="agnoster"

# Uncomment the following line to use case-sensitive completion.
CASE_SENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
DISABLE_AUTO_UPDATE="true"

ZSH_DISABLE_COMPFIX=true


HIST_STAMPS="mm/dd/yyyy"

HISTSIZE=1000
SAVEHIST=1000

plugins=(
    aws
    flutter
    git
    golang
    kubectl
    terraform
    zsh-autosuggestions
    zsh-syntax-highlighting
)

source $ZSH/oh-my-zsh.sh

# autoload -U compinit && compinit
# User configuration

export GO111MODULE=on
export GOPATH=$HOME/Golang
# export NVM_DIR=$HOME/.nvm
export PYENV_ROOT=$HOME/.pyenv
export PATH=$PATH:$GOPATH/bin:$PYENV_ROOT/bin

#
# Functions
#
[ -s "$HOME/.functions" ] && . "$HOME/.functions"

#
# Aliases
#
[ -s "$HOME/.aliases" ] && . "$HOME/.aliases"

#
# Bindkeys
#
bindkey "^U" backward-kill-line
bindkey "^X\\x7f" backward-kill-line
bindkey "^X^_" redo


# [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
if which pyenv > /dev/null; then eval "$(pyenv init -)"; fi

# change prompt
prompt_context() {
  if [[ "$USER" != "$DEFAULT_USER" || -n "$SSH_CLIENT" ]]; then
    prompt_segment black default "%(!.%{%F{yellow}%}.)%n"
  fi
}

### Fix slowness of pastes with zsh-syntax-highlighting.zsh
pasteinit() {
  OLD_SELF_INSERT=${${(s.:.)widgets[self-insert]}[2,3]}
  zle -N self-insert url-quote-magic # I wonder if you'd need `.url-quote-magic`?
}
pastefinish() {
  zle -N self-insert $OLD_SELF_INSERT
}
zstyle :bracketed-paste-magic paste-init pasteinit
zstyle :bracketed-paste-magic paste-finish pastefinish
### Fix slowness of pastes
source ~/.zsh/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh